# fly.toml app configuration file generated for twitterclone-fragrant-field-707 on 2024-08-19T15:12:26-03:00

app = 'twitterclone-fragrant-field-707'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[processes]
  app = "gunicorn --bind :8000 --workers 2 twitterclone.wsgi"
