# Generated by Django 5.0.7 on 2024-08-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="user",
        ),
    ]
