# Generated by Django 5.0.7 on 2024-08-19 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_tweet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
    ]
